### ISSUE TITLE
YOL HARİTASI

### ISSUE THREAD

**Issue by ahmetharuncelik** [ahmetharuncelik/COKsoftware#1]
Udemy'de 13. bölüme kadar mustafa murak ve yazbel üzerinden gidilecek. Notlar alınacak.

**Comment by BeyazAtliKarabasan** [comment]
gelinen yere kadar onlarca alıştırma çözülecek. github üzerinden ödev olarak verilecek.

**Comment by ahmetharuncelik** [comment]
Gelinen yere kadar onlarca alıştırma github üzerinden ödev verilecek.
